import browser from "webextension-polyfill"

// Ignore the no-console lint rule since this file is meant to funnel output to
// the console.
/* eslint-disable no-console */

const HOUR = 1000 * 60 * 60

// Every level's blob is restricted to the last 50k characters to avoid
// excess resource usage. This cap is part of the on-disk format contract:
// serializeLogs and the log export UI both assume any stored blob is at most
// this long.
export const MAX_LOG_CHARACTERS = 50000

// How long to wait after the *last* log line for a level before flushing its
// buffered lines to storage (a trailing debounce: each new line pushes the
// deadline back out).
export const FLUSH_DEBOUNCE_MS = 2000

// If buffered-but-unflushed data for a level grows past this many
// characters, flush immediately rather than waiting out the debounce. This
// bounds how much would be lost if the service worker were killed mid-burst.
export const FLUSH_THRESHOLD_CHARACTERS = 16 * 1024

const store = {
  async get(key: string): Promise<string> {
    const realKey = `logs-${key}`
    return String((await browser.storage.local.get(realKey))[realKey]) ?? ""
  },
  async getAll<T extends string[], Keys extends T[number]>(
    ...keys: Keys[]
  ): Promise<{ [key in Keys]: string }> {
    const keyResults = await browser.storage.local.get(
      keys.map((key) => `logs-${key}`),
    )
    return Object.fromEntries(
      keys.map<[Keys, string]>((key) => [
        key,
        String(keyResults[`logs-${key}`]) ?? "",
      ]),
    ) as { [key in Keys]: string }
  },
  /**
   * Writes one or more level blobs to storage in a single call. Flushing
   * several levels through this at once (rather than one `storage.local.set`
   * per level) is what lets bursts across levels coalesce into a single
   * IPC round-trip instead of several.
   */
  async setMany(entries: Partial<Record<string, string>>): Promise<void> {
    const payload = Object.fromEntries(
      Object.entries(entries).map(([key, value]) => [`logs-${key}`, value]),
    )
    await browser.storage.local.set(payload)
  },
}

export enum LogLevel {
  debug = "debug",
  info = "info",
  warn = "warn",
  error = "error",
  off = "off",
}

const logLevels = {
  [LogLevel.debug]: 0,
  [LogLevel.info]: 1,
  [LogLevel.warn]: 2,
  [LogLevel.error]: 3,
  [LogLevel.off]: 4,
}

interface LogStyle {
  icon: string
  css: string[]
  dateCss?: string[]
}

interface LogStyles {
  debug: LogStyle & { dateCss: string[] }
  log: LogStyle
  info: LogStyle
  warn: LogStyle
  error: LogStyle
}

const styles: LogStyles = {
  debug: {
    icon: "🐛",
    css: [],
    dateCss: ["float: right"],
  },
  log: {
    icon: "🪵",
    css: [],
  },
  info: {
    icon: "💡",
    css: ["color: blue"],
  },
  warn: {
    icon: "⚠️",
    css: [
      "color: #63450b",
      "background-color: #fffbe5",
      "border: 1px solid #fff5c2",
      "padding: 0.5em",
    ],
  },
  error: {
    icon: "❌",
    css: [
      "color: #ff1a1a",
      "background-color: #fff0f0",
      "border: 1px solid #ffd6d6",
      "padding: 0.5em",
    ],
  },
}

function purgeSensitiveFailSafe(log: string): string {
  // 1. Hexadecimal segments
  // 2. Private key length segments
  // 3. Lowercase groups of 12 words, which therefore covers 24

  return log.replaceAll(
    /0x[0-9a-fA-F]+|(\b[a-zA-Z0-9]{64}\b)|(?:[a-z]+(?:\s|$)){12}/g,
    "[REDACTED]",
  )
}

const BLINK_PREFIX = "    at "
const WEBKIT_GECKO_DELIMITER = "@"
const WEBKIT_MARKER = "@"
const GECKO_MARKER = "/"

function logLabelFromStackEntry(
  stackEntry: string | undefined,
): string | undefined {
  // Blink-ish.
  if (stackEntry?.startsWith(BLINK_PREFIX)) {
    // "    at [Class.][function] (... source file ...)
    return stackEntry.substring(BLINK_PREFIX.length).split(" ")[0]
  }

  // Fall back to Gecko-ish.
  if (
    stackEntry?.includes(GECKO_MARKER) &&
    stackEntry.includes(WEBKIT_GECKO_DELIMITER)
  ) {
    // "[path/to/Class/]method<?[/internal<?]@(... source file ...)"
    return stackEntry
      .split(WEBKIT_GECKO_DELIMITER)[0]
      .split(GECKO_MARKER)
      .filter((item) => item.replace(/(?:promise)?</, "").trim() !== "")
      .slice(-2)
      .join(".")
  }

  // WebKit-ish.
  if (stackEntry?.includes(WEBKIT_MARKER)) {
    // "[function]@(... source ...)
    return stackEntry.split(WEBKIT_MARKER)[0]
  }

  return undefined
}

// The length of an ISO8601 date string.
const iso8601Length = 24
// A regular expression that matches ISO8601 date strings as generated by
// `Date.toISOString()`.
const iso8601DateRegExpString =
  "\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+(?:[+-][0-2]\\d:[0-5]\\d|Z)"
// Matches start-of-line ISO dates in brackets with a space and bracket
// following, matching our serliazed logging pattern. A zero-width positive
// lookahead is used so that a split using this regex will not consume the date
// when splitting.
const logDateRegExp = new RegExp(
  `(?=^\\[${iso8601DateRegExpString}\\] \\[)`,
  "m",
)

type StorableLogLevel = Exclude<LogLevel, LogLevel.off>

/**
 * In-memory state for a single level's log blob. Storage is read at most
 * once per level per `Logger` instance (see `ensureLevelLoaded`); after
 * that, `blob` is the source of truth and storage is write-only, updated by
 * `flushAllDirty` on a debounce/threshold/immediate trigger.
 */
interface LevelCacheEntry {
  /** The full current blob for this level, once the initial load resolves. */
  blob: string | undefined
  /** In-flight initial load, so concurrent early appends for a level share
   * one `storage.local.get` instead of racing to issue their own. */
  loadPromise: Promise<string> | undefined
  /** Characters appended since the blob was last written to storage. */
  pendingCharacters: number
}

/**
 * The logger buffers each level's log blob in memory and writes it to
 * `browser.storage.local` only periodically, rather than doing a
 * read-modify-write round-trip on every single log line. `storage.local` is
 * a serialized IPC queue, so under load the old per-line
 * get+append+truncate+set pattern could enqueue hundreds of ~100KB
 * round-trips, starving every other consumer of storage.local (including the
 * popup's redux state read) — this was measured backing up to 67-second
 * single-op latencies under service-worker throttling.
 *
 * Flush triggers, in priority order:
 *  - `error` logs flush immediately, bypassing the buffer entirely: they're
 *    the lines most worth surviving a service-worker death.
 *  - Any other level flushes immediately once its unflushed buffer exceeds
 *    `FLUSH_THRESHOLD_CHARACTERS`, so a sustained burst can't grow the loss
 *    window without bound.
 *  - Otherwise, a level flushes after `FLUSH_DEBOUNCE_MS` of quiet (a
 *    trailing debounce shared across levels), so a handful of log lines
 *    coalesce into one write instead of one write apiece.
 *  - Whenever any of the above fires, every other level with unflushed data
 *    at that moment is opportunistically flushed in the same
 *    `storage.local.set` call (see `store.setMany`), so bursts across
 *    levels coalesce into one IPC round-trip rather than several.
 *
 * Accepted loss window: non-error levels can lose up to ~`FLUSH_DEBOUNCE_MS`
 * (or `FLUSH_THRESHOLD_CHARACTERS`) worth of buffered lines if the service
 * worker is terminated before a flush fires. MV3 gives no reliable
 * "about to be killed" hook to flush on synchronously, so this is a
 * deliberate trade: bounded data loss in the uncommon case in exchange for
 * not starving storage.local for every other consumer in the common case.
 * Note this loss is soft: each flush writes the *entire* in-memory blob, not
 * a diff, so as long as a later flush succeeds while the data is still
 * within the blob's 50k-character window, a previously-lost/failed flush is
 * naturally recovered.
 *
 * Cross-context note: this module is instantiated separately in the
 * background service worker and in each UI page (see `ui/index.ts` setting
 * `logger.contextId = "UI"` on its own copy of this singleton) — they are
 * different JS realms with independent in-memory caches, but both write the
 * *same* `logs-<level>` storage keys. This was already last-writer-wins
 * before this change (each line's read-modify-write picked up whatever was
 * most recently stored); it still is, but the window in which one context's
 * unflushed lines can be clobbered by the other's flush is now as wide as
 * the debounce/threshold rather than a single log line. This is a knowing
 * trade-off, not a bug: no cross-context locking is introduced here.
 */
export class Logger {
  /**
   * Minimum level to output
   */
  #level = logLevels[LogLevel.debug]

  set logLevel(value: LogLevel) {
    this.#level = logLevels[value]
  }

  private store = store

  private levelCaches: Partial<Record<StorableLogLevel, LevelCacheEntry>> = {}

  private flushTimer: ReturnType<typeof setTimeout> | undefined

  constructor(public contextId: string = "BG") {}

  debug(...input: unknown[]): void {
    this.logEvent(LogLevel.debug, input)
  }

  info(...input: unknown[]): void {
    this.logEvent(LogLevel.info, input)
  }

  warn(...input: unknown[]): void {
    this.logEvent(LogLevel.warn, input)
  }

  error(...input: unknown[]): void {
    this.logEvent(LogLevel.error, input)
  }

  /**
   * Helper for a common pattern where `Promise.allSettled` is used to
   * run multiple promises in parallel to resolve data, and some of the
   * promises may fail and should be logged as such.
   *
   * If no promises fail, nothing is logged. If promises fail, the
   * promise is logged alongside the corresponding entry in
   * `perResultData`, if any. This allows for `perResultData` to include
   * additional information about the failed promise. For example, if the
   * promises are resolving information about a set of addresses, the
   * perResultData might include the address corresponding to each promise, so
   * that a failure to resolve information about an address can include that
   * address alongside the failure for further debugging.
   */
  errorLogRejectedPromises<T>(
    logPrefix: string,
    settledPromises: PromiseSettledResult<T>[],
    perResultData: unknown[] = [],
  ): void {
    const rejectedLogData = settledPromises.reduce<unknown[]>(
      (logData, settledPromise, i) =>
        settledPromise.status === "rejected"
          ? [...logData, settledPromise, ...perResultData.slice(i, i + 1)]
          : logData,
      [],
    )

    if (rejectedLogData.length > 0) {
      this.error(logPrefix, rejectedLogData)
    }
  }

  buildError(...input: unknown[]): Error {
    this.error(...input)
    return new Error(input.join(" "))
  }

  logEvent(level: Exclude<LogLevel, LogLevel.off>, input: unknown[]): void {
    if (logLevels[level] < this.#level) return

    const stackTrace = new Error().stack
      ?.split("\n")
      ?.filter((line) => {
        // Remove empty lines from the output
        // Chrome prepends the word "Error" to the first line of the trace, but Firefox doesn't
        // Let's ignore that for consistency between browsers!
        if (line.trim() === "" || line.trim() === "Error") {
          return false
        }

        return true
      })
      // The first two lines of the stack trace will always be generated by this
      // file, so let's ignore them.
      ?.slice(2)

    const logLabel =
      logLabelFromStackEntry(stackTrace?.[0]) ?? "(unknown function)"
    const isoDateString = new Date().toISOString()
    const [logDate, logTime] = isoDateString.replace(/Z$/, "").split(/T/)

    console.group(
      `%c ${styles[level].icon} [${logTime}] ${logLabel} %c [${logDate}]`,
      styles[level].css.join(";"),
      styles[level].dateCss ?? styles.debug.dateCss.join(";"),
    )

    console[level](...input)

    // Suppress displaying stack traces when we use console.error()
    // since the browser already does that
    if (typeof stackTrace !== "undefined" && level !== "error") {
      console[level](stackTrace.join("\n"))
    }

    console.groupEnd()

    this.saveLog(level, isoDateString, logLabel, input, stackTrace)
  }

  private getOrCreateLevelCache(level: StorableLogLevel): LevelCacheEntry {
    let entry = this.levelCaches[level]

    if (!entry) {
      entry = { blob: undefined, loadPromise: undefined, pendingCharacters: 0 }
      this.levelCaches[level] = entry
    }

    return entry
  }

  /**
   * Warms the in-memory cache for a level from storage, at most once per
   * level for this `Logger` instance's lifetime. Concurrent calls for the
   * same not-yet-loaded level share a single in-flight `storage.local.get`
   * rather than each issuing their own.
   */
  private async ensureLevelLoaded(
    level: StorableLogLevel,
  ): Promise<LevelCacheEntry> {
    const entry = this.getOrCreateLevelCache(level)

    if (entry.blob === undefined) {
      entry.loadPromise ??= this.store.get(level)

      const loadedBlob = await entry.loadPromise

      // Only populate from the load if nothing has set the blob in the
      // meantime; defensive, since in practice the code between here and
      // any write to `entry.blob` never awaits (see `saveLog`).
      if (entry.blob === undefined) {
        entry.blob = loadedBlob
      }
    }

    return entry
  }

  private clearScheduledFlush(): void {
    if (this.flushTimer !== undefined) {
      clearTimeout(this.flushTimer)
      this.flushTimer = undefined
    }
  }

  private scheduleDebouncedFlush(): void {
    // A trailing debounce: each call pushes the deadline back out, so a
    // steady trickle of log lines only flushes once things go quiet (the
    // threshold check elsewhere is what bounds a sustained burst instead).
    this.clearScheduledFlush()
    this.flushTimer = setTimeout(() => {
      this.flushAllDirty().catch(() => {
        // Best-effort: nothing to retry here immediately. Each flush writes
        // the full in-memory blob rather than a diff, so a later successful
        // flush (triggered by the next log line) will naturally include
        // whatever this failed attempt was carrying, as long as it's still
        // within the level's 50k-character window.
      })
    }, FLUSH_DEBOUNCE_MS)
  }

  /**
   * Flushes every level with unflushed data to storage in a single
   * `storage.local.set` call, opportunistically coalescing whichever levels
   * happen to be dirty at the moment a flush is triggered (by debounce,
   * threshold, or an immediate `error` log).
   */
  private flushAllDirty(): Promise<void> {
    this.clearScheduledFlush()

    const dirtyLevels = (
      Object.keys(this.levelCaches) as StorableLogLevel[]
    ).filter((level) => (this.levelCaches[level]?.pendingCharacters ?? 0) > 0)

    if (dirtyLevels.length === 0) {
      return Promise.resolve()
    }

    const payload: Partial<Record<StorableLogLevel, string>> = {}

    dirtyLevels.forEach((level) => {
      const entry = this.levelCaches[level]

      if (entry) {
        payload[level] = entry.blob ?? ""
        entry.pendingCharacters = 0
      }
    })

    return this.store.setMany(payload)
  }

  private async saveLog(
    level: StorableLogLevel,
    isoDateString: string,
    logLabel: string,
    input: unknown[],
    stackTrace: string[] | undefined,
  ) {
    const formattedInput = input
      .map((loggedValue) => {
        if (typeof loggedValue === "object") {
          try {
            return JSON.stringify(loggedValue)
          } catch (_) {
            // If we can't stringify thats OK, we'll still see [object Object] or
            // null in the logs.
            return String(loggedValue)
          }
        } else {
          return String(loggedValue)
        }
      })
      .join(" ")

    const formattedStackTrace =
      stackTrace === undefined ? "" : `\n${stackTrace.join("\n")}`

    // Indent formatted input under the parent.
    const logData = `    ${formattedInput}${formattedStackTrace}`
      .split("\n")
      .join("\n    ")

    const fullPrefix = `[${isoDateString}] [${level.toUpperCase()}:${
      this.contextId
    }]`

    const purgedData = purgeSensitiveFailSafe(logData)
    const newEntry = `${fullPrefix} ${logLabel}\n${purgedData}\n\n`

    const entry = await this.ensureLevelLoaded(level)

    // Note: we have to do everything from here to updating `entry.blob`
    // synchronously, i.e. no promises, otherwise a concurrent `saveLog` call
    // in this same context could interleave a read of `entry.blob` with a
    // write to it and silently drop a line. (Cross-context interleaving —
    // e.g. between the background service worker and a UI page — is a
    // separate, already-accepted last-writer-wins trade-off; see the
    // class-level comment.)
    entry.blob = `${entry.blob}${newEntry}`
      // Restrict each log level to hold the last 50k characters to avoid excess resource
      // usage.
      .slice(-MAX_LOG_CHARACTERS)
    entry.pendingCharacters += newEntry.length

    if (level === LogLevel.error) {
      // Error lines are the ones most worth surviving a service-worker
      // death, so they skip the debounce/threshold buffering and flush
      // right away (opportunistically taking any other dirty level along
      // for the ride).
      await this.flushAllDirty()
    } else if (entry.pendingCharacters >= FLUSH_THRESHOLD_CHARACTERS) {
      await this.flushAllDirty()
    } else {
      this.scheduleDebouncedFlush()
    }
  }

  async serializeLogs(): Promise<string> {
    type StoredLogData = {
      -readonly [level in Exclude<LogLevel, LogLevel.off>]: string
    }

    // Flush this context's buffered-but-not-yet-persisted lines first, so
    // export reflects logs generated moments ago rather than only what has
    // already made it to storage.
    await this.flushAllDirty()

    const logs: StoredLogData = await this.store.getAll(
      "debug",
      "info",
      "warn",
      "error",
    )

    if (Object.values(logs).every((entry) => entry === "")) {
      return "[NO LOGS FOUND]"
    }

    const logEntries = Object.values(logs).flatMap((levelLogs) => {
      const splitLogs = levelLogs?.split(logDateRegExp) ?? []
      // If the date of the first element got cut off, use the 0 date for it.
      if (
        splitLogs.length > 0 &&
        splitLogs[0] !== "" &&
        !splitLogs[0].match(logDateRegExp)
      ) {
        splitLogs[0] = `[${new Date(0).toISOString()}] ${splitLogs[0]}`
      }

      return splitLogs
    })

    // This check is here to safeguard array access in the filter below
    if (logEntries.length < 1) {
      return ""
    }

    const dateFromLogEntry = (dateStr: string) =>
      new Date(dateStr.substring(1, iso8601Length))

    const entriesByDateAsc = logEntries
      // Sort by date.
      .sort((a, b) =>
        a.substr(1, iso8601Length).localeCompare(b.substr(1, iso8601Length)),
      )

    const lastEntry = entriesByDateAsc[entriesByDateAsc.length - 1]
    const lastEntryDate = dateFromLogEntry(lastEntry)

    return entriesByDateAsc // Only grab logs from the last available hour
      .filter(
        (logLine) =>
          dateFromLogEntry(logLine).getTime() >= lastEntryDate.getTime() - HOUR,
      )
      .join("\n")
  }
}

const logger = new Logger()

/**
 * Takes the same parameters as `Logger.errorLogRejectedPromises` and logs any
 * failed promises by calling that.
 *
 * This helper also unwraps all *fulfilled* promises and returns the results. That
 * allows a caller who wants to log failures and then deal with successes in one
 * step to call this function once with the `await Promise.allSettled` call as the
 * second parameter, and assign the result directly to a variable that is used
 * in downstream work.
 */
export function logRejectedAndReturnFulfilledResults<T>(
  logPrefix: string,
  settledPromises: PromiseSettledResult<T>[],
  perResultData: unknown[] = [],
): T[] {
  logger.errorLogRejectedPromises(logPrefix, settledPromises, perResultData)

  return settledPromises.reduce<T[]>(
    (fulfilledResults, settledPromise) =>
      settledPromise.status === "fulfilled"
        ? [...fulfilledResults, settledPromise.value]
        : fulfilledResults,
    [],
  )
}

export const serializeLogs = logger.serializeLogs.bind(logger)

export default logger
