// eslint-disable no-console

enum LogLevel {
  Log = "log",
  Info = "info",
  Warn = "warn",
  Error = "error",
}

function genericLogger(level: LogLevel, input: any[]) {
  console[level].apply(this, input)

  const stackTrace = new Error().stack.split("\n").filter((line) => {
    // Remove empty lines from the output
    // Chrome prepends the word "Error" to the first line of the trace, but Firefox doesn't
    // Let's ignore that for consistency between browsers!
    if (line.trim() === "" || line.trim() === "Error") {
      return false
    }

    return true
  })

  // The first two lines of the stack trace will always be generated by this file, so let's ignore them
  console[level](stackTrace.slice(2))
}

const logger = {
  log(...input: any[]) {
    genericLogger(LogLevel.Log, input)
  },

  info(...input: any[]) {
    genericLogger(LogLevel.Info, input)
  },

  warn(...input: any[]) {
    genericLogger(LogLevel.Warn, input)
  },

  error(...input: any[]) {
    genericLogger(LogLevel.Error, input)
  },
}

export default logger
