export const HIDE_ADD_SEED = process.env.HIDE_ADD_SEED === "true"
export const HIDE_SEND_BUTTON = process.env.HIDE_SEND_BUTTON === "true"
export const HIDE_EARN_PAGE = process.env.HIDE_EARN_PAGE === "true"
export const HIDE_SWAP = process.env.HIDE_SWAP === "true"
export const HIDE_IMPORT_DERIVATION_PATH =
  process.env.HIDE_IMPORT_DERIVATION_PATH === "true"
export const HIDE_CREATE_PHRASE = process.env.HIDE_CREATE_PHRASE === "true"
export const HIDE_IMPORT_LEDGER = process.env.HIDE_IMPORT_LEDGER === "true"
export const HIDE_IMPORT_TREZOR = process.env.HIDE_IMPORT_TREZOR === "true"
export const PERSIST_UI_LOCATION = process.env.PERSIST_UI_LOCATION === "true"
export const USE_MAINNET_FORK = process.env.USE_MAINNET_FORK === "true"
