export enum FeatureFlagTypes {
  HIDE_IMPORT_DERIVATION_PATH,
  USE_MAINNET_FORK,
  HIDE_SWAP_REWARDS,
  RESOLVE_RNS_NAMES,
  SUPPORT_GOERLI,
  SUPPORT_ARBITRUM,
  HIDE_TOKEN_FEATURES,
  USE_UPDATED_SIGNING_UI,
  USE_BALANCE_RELOADER,
  SUPPORT_MULTIPLE_LANGUAGES,
  SUPPORT_ANALYTICS,
  SUPPORT_TABBED_ONBOARDING,
  SUPPORT_KEYRING_LOCKING,
  SUPPORT_FORGOT_PASSWORD,
  ENABLE_ACHIEVEMENTS_TAB,
}

export const isEnabled = (type: FeatureFlagTypes): boolean =>
  (localStorage.getItem(FeatureFlagTypes[type]) ||
    (process.env[FeatureFlagTypes[type]] ?? "false")) === "true"
