export const HIDE_EARN_PAGE = process.env.HIDE_EARN_PAGE === "true"
export const HIDE_IMPORT_DERIVATION_PATH =
  process.env.HIDE_IMPORT_DERIVATION_PATH === "true"
export const PERSIST_UI_LOCATION = process.env.PERSIST_UI_LOCATION === "true"
export const USE_MAINNET_FORK = process.env.USE_MAINNET_FORK === "true"
export const HIDE_SWAP_REWARDS = process.env.HIDE_SWAP_REWARDS === "true"
export const RESOLVE_RNS_NAMES = process.env.RESOLVE_RNS_NAMES === "true"
export const MULTI_NETWORK = process.env.MULTI_NETWORK === "true"
export const CUSTOM_GAS_SELECT = process.env.CUSTOM_GAS_SELECT === "true"
export const HIDE_TOKEN_FEATURES = process.env.HIDE_TOKEN_FEATURES === "true"
